export const MUTATIONS_TYPES = {
    SET_RECIPE: "SET_RECIPE",
    SET_RECIPE_SEARCH_QUERY: "SET_RECIPE_SEARCH_QUERY",
    SET_RECIPE_SEARCH_RESULTS: "SET_RECIPE_SEARCH_RESULTS"
}

export const ACTIONS_TYPES = {
    GET_RECIPE: "GET_RECIPE",
    GET_RANDOM_RECIPE: "GET_RANDOM_RECIPE",
    SEARCH_RECIPE_BY_NAME: "SEARCH_RECIPE_BY_NAME"
}