export const MUTATIONS_TYPES = {
    SET_RECIPE: "SET_RECIPE",
    SET_RECIPE_SEARCH_QUERY: "SET_RECIPE_SEARCH_QUERY",
    SET_RECIPES_LIST: "SET_RECIPES_LIST",
    SET_IS_LOADING: "SET_IS_LOADING",
    CLEAR_RECIPES_LIST: "CLEAR_RECIPES_LIST",
    SET_RECIPES_CATEGORIES: "SET_RECIPES_CATEGORIES",
    SET_PICKED_CATEGORY: "SET_PICKED_CATEGORY",
    ADD_RECIPE: "ADD_RECIPE",
    REMOVE_RECIPE: "REMOVE_RECIPE",
    SET_SAVED_RECIPES: "SET_SAVED_RECIPES",
    SET_SAVED_RECIPES: "SET_SAVED_RECIPES",
    SET_AREAS: "SET_AREAS",
    CLEAR_RECIPE: "CLEAR_RECIPE"
}

export const ACTIONS_TYPES = {
    GET_RECIPE: "GET_RECIPE",
    GET_RANDOM_RECIPE: "GET_RANDOM_RECIPE",
    SEARCH_RECIPE_BY_NAME: "SEARCH_RECIPE_BY_NAME",
    GET_RECIPES_CATEGORIES: "GET_RECIPES_CATEGORIES",
    GET_RECIPES_BY_CATEGORY: "GET_RECIPES_BY_CATEGORY",
    SAVE_OR_REMOVE_RECIPE: "SAVE_OR_REMOVE_RECIPE",
    GET_SAVED_RECIPES: "GET_SAVED_RECIPES",
    GET_SAVED_RECIPES_DATA: "GET_SAVED_RECIPES_DATA",
    GET_AREAS: "GET_AREAS",
    GET_RECIPES_BY_AREA: "GET_RECIPES_BY_AREA"
}